# Generated by Django 4.2.1 on 2023-06-11 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mac_address_types", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MacAddessType",
            new_name="MacAddressType",
        ),
    ]
