# Generated by Django 4.2.1 on 2023-06-11 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0003_alter_macaddresstype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macaddresstype",
            options={
                "managed": True,
                "verbose_name": "MAC Address Type",
                "verbose_name_plural": "MAC Address Types",
            },
        ),
    ]
