# Generated by Django 4.2.1 on 2023-06-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0004_alter_macaddresstype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="macaddresstype",
            name="desc",
            field=models.TextField(max_length=600, null=True),
        ),
    ]
