# Generated by Django 4.2.1 on 2023-06-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0005_macaddresstype_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macaddresstype",
            name="desc",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
