# Generated by Django 4.2.1 on 2023-06-12 03:52

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0007_alter_macaddresstype_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="macaddresstype",
            name="active_from",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="macaddresstype",
            name="active_until",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2501, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
