# Generated by Django 4.2.1 on 2023-06-12 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0009_alter_macaddresstype_active_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macaddresstype",
            name="active_until",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2501, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
