# Generated by Django 4.2.2 on 2023-06-25 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mac_address_types", "0014_alter_macaddresstype_active_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macaddresstype",
            name="active_from",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
