# Generated by Django 4.2.1 on 2023-05-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=6, null=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("ipv4", models.GenericIPAddressField(protocol="IPv4")),
                ("ipv6", models.GenericIPAddressField(protocol="IPv6")),
                (
                    "created_by",
                    models.ForeignKey(
                        default="NONAME",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default="NONAME",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "db_table": "devices",
                "db_table_comment": "Devices to be managed such as Webcam, Sensors, System-On-Module (SOM)",
                "managed": True,
                "indexes": [models.Index(fields=["name"], name="devices_ix01")],
            },
        ),
    ]
