# Generated by Django 4.2.1 on 2023-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_alter_device_ipv4_alter_device_ipv6"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ipv4",
            field=models.GenericIPAddressField(
                blank=True, default=None, null=True, protocol="IPv4"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="ipv6",
            field=models.GenericIPAddressField(
                blank=True, default=None, null=True, protocol="IPv6"
            ),
        ),
    ]
