# Generated by Django 4.2.2 on 2023-06-18 06:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_alter_device_created_by_alter_device_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="active_from",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="active_until",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2501, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
