# Generated by Django 4.2.3 on 2023-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0009_alter_device_active_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="code",
            field=models.CharField(default="xxxxx", max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
