# Generated by Django 4.2.3 on 2023-08-27 05:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0004_alter_customer_active_from"),
        ("devices", "0010_alter_device_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviCustAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_from",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "active_until",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2501, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "closing_reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCH", "Scheduled"),
                            ("EOC", "End of Contract"),
                            ("DEC", "Decommissioned"),
                            ("OOO", "Out Of Order"),
                        ],
                        max_length=3,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "closing_remarks",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Customer Assignment",
                "verbose_name_plural": "Device Customer Assignments",
                "db_table": "devi_cust_assignments",
                "db_table_comment": "Assignments of devices to customers",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="device",
            name="customers",
            field=models.ManyToManyField(
                related_name="devices",
                through="devices.DeviCustAssignment",
                to="customers.customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicustassignment",
            constraint=models.UniqueConstraint(
                fields=("customer", "device", "active_from"),
                name="devi_cust_assignment_uk01",
            ),
        ),
    ]
