# Generated by Django 4.2.3 on 2023-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0011_devicustassignment_device_customers_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="devicustassignment",
            name="devi_cust_assignment_uk01",
        ),
    ]
