# Generated by Django 4.2.3 on 2023-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_customer_active_from"),
        ("devices", "0013_remove_device_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="customers",
            field=models.ManyToManyField(
                related_name="devices",
                through="devices.DeviCustAssignment",
                to="customers.customer",
            ),
        ),
    ]
