# Generated by Django 4.2.3 on 2023-08-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0014_device_customers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="devicustassignment",
            constraint=models.UniqueConstraint(
                fields=("customer", "device", "active_from"),
                name="devi_cust_assignment_uk01",
            ),
        ),
    ]
