# Generated by Django 4.2.3 on 2023-09-15 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0015_devicustassignment_devi_cust_assignment_uk01"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="active",
        ),
        migrations.RemoveField(
            model_name="devicustassignment",
            name="active",
        ),
    ]
