# Generated by Django 4.2.1 on 2023-05-26 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "managed": True,
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
            },
        ),
    ]
