# Generated by Django 4.2.2 on 2023-06-18 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="active_from",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="active_until",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2501, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                related_query_name="%(app_label)s_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                related_query_name="%(app_label)s_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
