# Generated by Django 4.2.2 on 2023-06-14 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mac_address_types", "0013_alter_macaddresstype_active_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("address", models.CharField(max_length=17, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maad_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mac_address_types.macaddresstype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mac_address",
                "verbose_name_plural": "mac_addresses",
                "db_table": "mac_addresses",
                "db_table_comment": "MAC adresses",
                "managed": True,
                "indexes": [models.Index(fields=["address"], name="address_uk01")],
            },
        ),
    ]
