# Generated by Django 4.2.2 on 2023-06-15 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mac_addresses", "0002_macaddress_device"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macaddress",
            options={
                "managed": True,
                "verbose_name": "MAC Address",
                "verbose_name_plural": "MAC Addresses",
            },
        ),
    ]
