# Generated by Django 4.2.3 on 2023-10-03 18:26

from django.db import migrations, models

import mac_addresses.validators


class Migration(migrations.Migration):
    dependencies = [
        ("mac_addresses", "0008_alter_macaddress_active_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macaddress",
            name="address",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[mac_addresses.validators.validate_mac_address],
            ),
        ),
    ]
